### ISSUE TITLE
npTDMS Error (Invalid object path: /'Group'/'Channel1)

### ISSUE THREAD

**Issue by Darshanrrg** [adamreeve/npTDMS#141]
Hi I'm getting the following error while implementing the code. Kindly provide troubleshooting methods.
----
Traceback (most recent call last):
  File "C:\Users\Darshan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nptdms\tdms.py", line 101, in object
    return self.objects[object_path]
KeyError: "/'Group'/'Channel1'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Darshan/Desktop/TDMS.py", line 4, in <module>
    channel = tdms_file.object('Group', 'Channel1')
  File "C:\Users\Darshan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nptdms\tdms.py", line 103, in object
    raise KeyError("Invalid object path: %s" % object_path)
KeyError: "Invalid object path: /'Group'/'Channel1'"

-------------------

**Comment by adamreeve** [comment]
Hi,  this error means you don't have a channel in your tdms file named "Channel1" in group "Group". You  can use the `groups` method to get a list of all the group names in the file, then `group_channels` will give you all of the channel objects in a group. Or you can run the `tdmsinfo` command on your file to see what groups and channels it contains.
