### ISSUE TITLE
Support converting to pandas dataframe when opening without reading all data

### ISSUE THREAD

**Issue by suntracks** [adamreeve/npTDMS#209]
Have been using the new nptdms library, 
with this havent been able to convert the group to a pandas dataframe.

```
        with TdmsFile.open(file) as tdms_file:
            Mt = tdms_file['EEG_M(t)'].as_dataframe()
```
However this code used to work on earlier versions and not working on this version

```
tdms_file = TdmsFile(filepath)
for group in tdms_file.groups():
        EMG_Bt = tdms_file.object('EMG_B(t)').as_dataframe()

```
Libraries used

npTDMS==0.27.0
numpy==1.19.0
oauthlib==3.1.0
pandas==1.0.5

error trace

```
Traceback (most recent call last):
  File "D:\python\synphne code venv\lib\site-packages\nptdms\utils.py", line 25, in get
    return getattr(self, attr_name)
AttributeError: 'TdmsChannel' object has no attribute '_cached_prop_data'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:/Users/ss/PycharmProjects/untitled/testFile.py", line 25, in <module>
    tdms_data = [group.as_dataframe() for group in tdms_file.groups()]
  File "C:/Users/ss/PycharmProjects/untitled/testFile.py", line 25, in <listcomp>
    tdms_data = [group.as_dataframe() for group in tdms_file.groups()]
  File "D:\python\code venv\lib\site-packages\nptdms\tdms.py", line 470, in as_dataframe
    return pandas_export.from_group(self, time_index, absolute_time, scaled_data)
  File "D:\python\ code venv\lib\site-packages\nptdms\export\pandas_export.py", line 41, in from_group
    return _channels_to_dataframe(channels_to_export, time_index, absolute_time, scaled_data)
  File "D:\python\ code venv\lib\site-packages\nptdms\export\pandas_export.py", line 69, in _channels_to_dataframe
    dataframe_dict[column_name] = pd.Series(data=_array_for_pd(channel.data), index=index)
  File "D:\python\code venv\lib\site-packages\nptdms\utils.py", line 27, in get
    value = func(self)
  File "D:\python\code venv\lib\site-packages\nptdms\tdms.py", line 647, in data
    raise RuntimeError("Channel data has not been read")
RuntimeError: Channel data has not been read
During handling of the above exception, another exception occurred:
```

**Comment by adamreeve** [comment]
Hi, the problem here is that you've opened the file without reading all data immediately, and there isn't yet support for converting data to pandas in this scenario.

This should work instead:
```python
tdms_file = TdmsFile.read(file)
Mt = tdms_file['EEG_M(t)'].as_dataframe()
```
(note the use of `TdmsFile.read` instead of `TdmsFile.open`)
