### ISSUE TITLE
Problem with "as_frame"

### ISSUE THREAD

**Issue by mrejster** [adamreeve/npTDMS#70]
Hi, 
This script used to work,
``` python
#!/usr/bin/env python
from nptdms import TdmsFile
import matplotlib.pyplot as plt
from scipy import signal
from numpy import linspace

tdms_file = TdmsFile('cRIO.tdms')

frame=tdms_file.as_dataframe()
print frame.columns
```

after a while, and switching to Ubuntu 16.04 (probably unrelated), I get this error:

./plot_tdms.py 
WARNING:nptdms.tdms:Last segment of file has unknown size, not attempting to read it
Traceback (most recent call last):
  File "./plot_tdms.py", line 9, in <module>
    frame=tdms_file.as_dataframe()
  File "/usr/local/lib/python2.7/dist-packages/nptdms/tdms.py", line 225, in as_dataframe
    temp.append((key, pd.Series(data=value.data, index=index)))
  File "/usr/local/lib/python2.7/dist-packages/nptdms/tdms.py", line 716, in data
    scale = scaling.get_scaling(self)
  File "/usr/local/lib/python2.7/dist-packages/nptdms/scaling.py", line 29, in get_scaling
    return next(s for s in scalings if s is not None)
  File "/usr/local/lib/python2.7/dist-packages/nptdms/scaling.py", line 29, in <genexpr>
    return next(s for s in scalings if s is not None)
  File "/usr/local/lib/python2.7/dist-packages/nptdms/scaling.py", line 27, in <genexpr>
    scalings = (_get_object_scaling(o) for o in _tdms_hierarchy(channel))
  File "/usr/local/lib/python2.7/dist-packages/nptdms/scaling.py", line 51, in _get_object_scaling
    log.warning("Unsupported scale type: %s", scale_type)
NameError: global name 'log' is not defined

My data file indeed contains the "unknown scale type" strain.
I don't think that should generate a name-error though?
If I change "log" to "logging" in scaling.py, the warning is simply printed instead

Any suggestions?
Thanks
//Erik

**Comment by adamreeve** [comment]
Hi, thanks for reporting this. This is a bug introduced recently when I refactored the scaling code. If the scaling type isn't supported it just means no scaling will be applied, but this shouldn't cause a crash. This is now fixed in version 0.11.1.
