### ISSUE TITLE
Number of Scaling Polynomial Coefficients

### ISSUE THREAD

**Issue by GHoldgate** [adamreeve/npTDMS#77]
Accessing the TdmsFile().object("group","channel").data attribute wasn't working because the scaling was trying to iterate over a range of 4 "NI_Scale[0]_Polynomial_Coefficients" - throwing this error: 

```
Traceback (most recent call last):

  File "<ipython-input-1-f7d1024cb13e>", line 1, in <module>
    runfile('E:/ANALYSIS PROJECTS/12. Testing Postprocessing/Sohatex/testScript.py', wdir='E:/ANALYSIS PROJECTS/12. Testing Postprocessing/Sohatex')

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/ANALYSIS PROJECTS/12. Testing Postprocessing/Sohatex/testScript.py", line 17, in <module>
    data = channel.data

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\nptdms\tdms.py", line 777, in data
    scale = scaling.get_scaling(self)

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\nptdms\scaling.py", line 30, in get_scaling
    return next(s for s in scalings if s is not None)

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\nptdms\scaling.py", line 30, in <genexpr>
    return next(s for s in scalings if s is not None)

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\nptdms\scaling.py", line 28, in <genexpr>
    scalings = (_get_object_scaling(o) for o in _tdms_hierarchy(channel))

  File "C:\Users\gholdgate\AppData\Local\Continuum\Anaconda2\lib\site-packages\nptdms\scaling.py", line 45, in _get_object_scaling
    for i in range(4)]

KeyError: 'NI_Scale[0]_Polynomial_Coefficients[2]'
```
I found that the scaling function wasn't considering that different data sets could have different numbers of Polynomial Coefficient, so I fixed this on my local copy of the package by changing the _get_object_scaling method in the "scaling" file from this: 
```
def _get_object_scaling(obj):
    scale_index = _get_scale_index(obj.properties)
    if scale_index is None:
        return None

    scale_type = obj.properties['NI_Scale[%d]_Scale_Type' % scale_index]
    if scale_type == 'Polynomial':
        coefficients = [
            obj.properties[
                'NI_Scale[%d]_Polynomial_Coefficients[%d]' % (scale_index, i)]
            for i in range(4)]
        return PolynomialScaling(coefficients)
    elif scale_type == 'Linear':
        return LinearScaling(
            obj.properties["NI_Scale[%d]_Linear_Y_Intercept" % scale_index],
            obj.properties["NI_Scale[%d]_Linear_Slope" % scale_index])
    else:
        log.warning("Unsupported scale type: %s", scale_type)
        return None
```
to this:
```
def _get_object_scaling(obj):
    scale_index = _get_scale_index(obj.properties)
    if scale_index is None:
        return None

    scale_type = obj.properties['NI_Scale[%d]_Scale_Type' % scale_index]
    if scale_type == 'Polynomial':
        coefficients = [
            obj.properties[
                'NI_Scale[%d]_Polynomial_Coefficients[%d]' % (scale_index, i)]
            for i in range(obj.properties[
                'NI_Scale[%d]_Polynomial_Coefficients_Size' % (scale_index)])]
        return PolynomialScaling(coefficients)
    elif scale_type == 'Linear':
        return LinearScaling(
            obj.properties["NI_Scale[%d]_Linear_Y_Intercept" % scale_index],
            obj.properties["NI_Scale[%d]_Linear_Slope" % scale_index])
    else:
        log.warning("Unsupported scale type: %s", scale_type)
        return None
```
I have only started using this package today so I hope I haven't "fixed" intentional functionality.

**Comment by adamreeve** [comment]
Hi, apologies for the very long delay responding to this, and thanks a lot for reporting this bug and the fix. I've just pushed a commit to fix this in the master branch.
